name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3000

  build:
    needs: [cypress]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/weather-app-nextjs

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/weather-app-nextjs
